/**
 * Danh mục công cụ trên Bảng điều hướng (`/`).
 * Thêm mục mới: bổ sung object vào `NAVIGATION_BOARD_TOOLS`.
 */

export const NAVIGATION_BOARD_CATEGORIES = [
  { id: "all", labelKey: "navigationBoard.filterAll" },
  { id: "operations", labelKey: "navigationBoard.filterOperations" },
  { id: "hr", labelKey: "navigationBoard.filterHr" },
  { id: "finance", labelKey: "navigationBoard.filterFinance" },
  { id: "documents", labelKey: "navigationBoard.filterDocuments" },
  { id: "system", labelKey: "navigationBoard.filterSystem" },
];

/** @typedef {'active' | 'maintenance' | 'new'} NavigationBoardStatus */

/**
 * @type {readonly {
 *   id: string,
 *   path: string,
 *   category: string,
 *   titleKey: string,
 *   descriptionKey: string,
 *   status?: NavigationBoardStatus,
 *   adminOnly?: boolean,
 *   koreanOnly?: boolean,
 * }[]}
 */
export const NAVIGATION_BOARD_TOOLS = [
  {
    id: "APP-02",
    path: "/normal",
    category: "operations",
    titleKey: "navbar.sanLuong",
    descriptionKey: "navigationBoard.descSanLuong",
    status: "active",
  },
  {
    id: "APP-21",
    path: "/s90d-production-report",
    category: "operations",
    titleKey: "navbar.s90dProductionReport",
    descriptionKey: "navigationBoard.descS90dProductionReport",
    status: "new",
  },
  {
    id: "APP-03",
    path: "/performance",
    category: "operations",
    titleKey: "navbar.caiTien",
    descriptionKey: "navigationBoard.descPerformance",
    status: "active",
  },
  {
    id: "APP-04",
    path: "/nhietdo",
    category: "operations",
    titleKey: "navbar.nhietdo",
    descriptionKey: "navigationBoard.descTemperature",
    status: "active",
  },
  {
    id: "APP-05",
    path: "/mold",
    category: "operations",
    titleKey: "navbar.mold",
    descriptionKey: "navigationBoard.descMold",
    status: "active",
  },
  {
    id: "APP-06",
    path: "/qr-code-generator",
    category: "operations",
    titleKey: "navbar.qrCodeGenerator",
    descriptionKey: "navigationBoard.descQr",
    status: "active",
  },
  {
    id: "APP-07",
    path: "/mc-defect-report",
    category: "operations",
    titleKey: "navbar.mcDefectReport",
    descriptionKey: "navigationBoard.descMcDefect",
    status: "active",
  },
  {
    id: "APP-08",
    path: "/stock-variance",
    category: "finance",
    titleKey: "navbar.inventoryDashboard",
    descriptionKey: "navigationBoard.descStockVariance",
    status: "active",
  },
  {
    id: "APP-09",
    path: "/attendance-list",
    category: "hr",
    titleKey: "navbar.attendanceList",
    descriptionKey: "navigationBoard.descAttendanceList",
    status: "active",
  },
  {
    id: "APP-10",
    path: "/seasonal-staff-attendance",
    category: "hr",
    titleKey: "navbar.seasonalStaffAttendance",
    descriptionKey: "navigationBoard.descSeasonalStaff",
    status: "active",
  },
  {
    id: "APP-11",
    path: "/korean-timesheet",
    category: "hr",
    titleKey: "attendanceList.sidebarKoreanTimesheet",
    descriptionKey: "navigationBoard.descKoreanTimesheet",
    status: "new",
    koreanOnly: true,
  },
  {
    id: "APP-12",
    path: "/annual-leave",
    category: "hr",
    titleKey: "navbar.annualLeave",
    descriptionKey: "navigationBoard.descAnnualLeave",
    status: "active",
  },
  {
    id: "APP-13",
    path: "/attendance-dashboard",
    category: "hr",
    titleKey: "navbar.attendanceDashboard",
    descriptionKey: "navigationBoard.descAttendanceDashboard",
    status: "new",
  },
  {
    id: "APP-14",
    path: "/attendance-salary",
    category: "hr",
    titleKey: "navbar.attendanceSalary",
    descriptionKey: "navigationBoard.descPayroll",
    status: "active",
  },
  {
    id: "APP-15",
    path: "/bangkhen1",
    category: "documents",
    titleKey: "navbar.certificate1",
    descriptionKey: "navigationBoard.descCertificate1",
    status: "active",
    adminOnly: true,
  },
  {
    id: "APP-16",
    path: "/bangkhen2",
    category: "documents",
    titleKey: "navbar.certificate2",
    descriptionKey: "navigationBoard.descCertificate2",
    status: "active",
    adminOnly: true,
  },
  {
    id: "APP-17",
    path: "/honor-board",
    category: "documents",
    titleKey: "navbar.honorBoard",
    descriptionKey: "navigationBoard.descHonorBoard",
    status: "active",
    adminOnly: true,
  },
  {
    id: "APP-18",
    path: "/downloads",
    category: "documents",
    titleKey: "navbar.files",
    descriptionKey: "navigationBoard.descDownloads",
    status: "active",
  },
  {
    id: "APP-19",
    path: "/user-department",
    category: "system",
    titleKey: "navbar.userDepartment",
    descriptionKey: "navigationBoard.descUserDepartment",
    status: "active",
    adminOnly: true,
  },
  {
    id: "APP-20",
    path: "/permission-catalog",
    category: "system",
    titleKey: "navbar.permissionCatalog",
    descriptionKey: "navigationBoard.descPermissionCatalog",
    status: "active",
    adminOnly: true,
  },
];
