/**
 * Chỉ số cột grid (1-based). Khi một số ô `display:none`, auto-placement làm lệch % —
 * buộc mỗi ô đúng track để khớp `grid-template-columns`.
 */
export const ATTENDANCE_GRID_COL = {
  stt: 1,
  mnv: 2,
  mvt: 3,
  fullName: 4,
  gender: 5,
  joinDate: 6,
  workStatus: 7,
  deptCode: 8,
  dept: 9,
  annualLeaveBalance: 10,
  timeIn: 11,
  timeOut: 12,
  leaveType: 13,
  shift: 14,
  offDay: 15,
  holidayDay: 16,
  workingHours: 17,
  dayShiftOvertimeHours: 18,
  offDayOvertimeHours: 19,
  holidayDayWorkingHours: 20,
  payrollTotalGcDay: 21,
  nightShiftWorkingHours: 22,
  nightShiftOvertimeHours: 23,
  nightShiftOffDayWorkingHours: 24,
  holidayNightWorkingHours: 25,
  payrollTotalGcNight: 26,
  actions: 27,
};

/** Cùng thứ tự cột nhưng bỏ mã BP — % chia lại tròn 100. */
export const ATTENDANCE_GRID_COL_COMPACT_WITH_ACTIONS = {
  stt: 1,
  mnv: 2,
  mvt: 3,
  fullName: 4,
  gender: 5,
  dept: 6,
  annualLeaveBalance: 7,
  timeIn: 8,
  timeOut: 9,
  leaveType: 10,
  shift: 11,
  offDay: 12,
  holidayDay: 13,
  workingHours: 14,
  dayShiftOvertimeHours: 15,
  offDayOvertimeHours: 16,
  holidayDayWorkingHours: 17,
  payrollTotalGcDay: 18,
  nightShiftWorkingHours: 19,
  nightShiftOvertimeHours: 20,
  nightShiftOffDayWorkingHours: 21,
  holidayNightWorkingHours: 22,
  payrollTotalGcNight: 23,
  actions: 24,
};

export const ATTENDANCE_GRID_COL_COMPACT_NO_ACTIONS = {
  stt: 1,
  mnv: 2,
  mvt: 3,
  fullName: 4,
  gender: 5,
  dept: 6,
  annualLeaveBalance: 7,
  timeIn: 8,
  timeOut: 9,
  leaveType: 10,
  shift: 11,
  offDay: 12,
  holidayDay: 13,
  workingHours: 14,
  dayShiftOvertimeHours: 15,
  offDayOvertimeHours: 16,
  holidayDayWorkingHours: 17,
  payrollTotalGcDay: 18,
  nightShiftWorkingHours: 19,
  nightShiftOvertimeHours: 20,
  nightShiftOffDayWorkingHours: 21,
  holidayNightWorkingHours: 22,
  payrollTotalGcNight: 23,
};

/** Ẩn mã BP + bộ phận — 9 cột (có Sửa) hoặc 8 cột. */
export const ATTENDANCE_GRID_COL_NARROW_WITH_ACTIONS = {
  stt: 1,
  mnv: 2,
  mvt: 3,
  fullName: 4,
  gender: 5,
  annualLeaveBalance: 6,
  timeIn: 7,
  timeOut: 8,
  leaveType: 9,
  shift: 10,
  offDay: 11,
  holidayDay: 12,
  workingHours: 13,
  dayShiftOvertimeHours: 14,
  offDayOvertimeHours: 15,
  holidayDayWorkingHours: 16,
  payrollTotalGcDay: 17,
  nightShiftWorkingHours: 18,
  nightShiftOvertimeHours: 19,
  nightShiftOffDayWorkingHours: 20,
  holidayNightWorkingHours: 21,
  payrollTotalGcNight: 22,
  actions: 23,
};

export const ATTENDANCE_GRID_COL_NARROW_NO_ACTIONS = {
  stt: 1,
  mnv: 2,
  mvt: 3,
  fullName: 4,
  gender: 5,
  annualLeaveBalance: 6,
  timeIn: 7,
  timeOut: 8,
  leaveType: 9,
  shift: 10,
  offDay: 11,
  holidayDay: 12,
  workingHours: 13,
  dayShiftOvertimeHours: 14,
  offDayOvertimeHours: 15,
  holidayDayWorkingHours: 16,
  payrollTotalGcDay: 17,
  nightShiftWorkingHours: 18,
  nightShiftOvertimeHours: 19,
  nightShiftOffDayWorkingHours: 20,
  holidayNightWorkingHours: 21,
  payrollTotalGcNight: 22,
};

export const ATTENDANCE_GRID_COL_MINIMAL_WITH_ACTIONS = {
  mnv: 1,
  fullName: 2,
  timeIn: 3,
  leaveType: 4,
  shift: 5,
  offDay: 6,
  holidayDay: 7,
  workingHours: 8,
  dayShiftOvertimeHours: 9,
  offDayOvertimeHours: 10,
  holidayDayWorkingHours: 11,
  payrollTotalGcDay: 12,
  nightShiftWorkingHours: 13,
  nightShiftOvertimeHours: 14,
  nightShiftOffDayWorkingHours: 15,
  holidayNightWorkingHours: 16,
  payrollTotalGcNight: 17,
  actions: 18,
};

export const ATTENDANCE_GRID_COL_MINIMAL_NO_ACTIONS = {
  mnv: 1,
  fullName: 2,
  timeIn: 3,
  leaveType: 4,
  shift: 5,
  offDay: 6,
  holidayDay: 7,
  workingHours: 8,
  dayShiftOvertimeHours: 9,
  offDayOvertimeHours: 10,
  holidayDayWorkingHours: 11,
  payrollTotalGcDay: 12,
  nightShiftWorkingHours: 13,
  nightShiftOvertimeHours: 14,
  nightShiftOffDayWorkingHours: 15,
  holidayNightWorkingHours: 16,
  payrollTotalGcNight: 17,
};

/** Điểm danh: thêm cột Ngày off (OFF) — không khối cột giờ lương (khớp `dropSalaryHoursWidths` + chèn off). */
export const FULL_ATTENDANCE_ONLY_NO_ACTIONS = {
  stt: 1,
  mnv: 2,
  mvt: 3,
  fullName: 4,
  gender: 5,
  joinDate: 6,
  workStatus: 7,
  deptCode: 8,
  dept: 9,
  annualLeaveBalance: 10,
  timeIn: 11,
  timeOut: 12,
  leaveType: 13,
  shift: 14,
  offDay: 15,
  holidayDay: 16,
};
export const FULL_ATTENDANCE_ONLY_WITH_ACTIONS = {
  ...FULL_ATTENDANCE_ONLY_NO_ACTIONS,
  actions: 17,
};
export const COMPACT_ATTENDANCE_ONLY_NO_ACTIONS = {
  stt: 1,
  mnv: 2,
  mvt: 3,
  fullName: 4,
  gender: 5,
  dept: 6,
  annualLeaveBalance: 7,
  timeIn: 8,
  timeOut: 9,
  leaveType: 10,
  shift: 11,
  offDay: 12,
  holidayDay: 13,
};
export const COMPACT_ATTENDANCE_ONLY_WITH_ACTIONS = {
  ...COMPACT_ATTENDANCE_ONLY_NO_ACTIONS,
  actions: 14,
};
export const NARROW_ATTENDANCE_ONLY_NO_ACTIONS = {
  stt: 1,
  mnv: 2,
  mvt: 3,
  fullName: 4,
  gender: 5,
  annualLeaveBalance: 6,
  timeIn: 7,
  timeOut: 8,
  leaveType: 9,
  shift: 10,
  offDay: 11,
  holidayDay: 12,
};
export const NARROW_ATTENDANCE_ONLY_WITH_ACTIONS = {
  ...NARROW_ATTENDANCE_ONLY_NO_ACTIONS,
  actions: 13,
};
export const MINIMAL_ATTENDANCE_ONLY_NO_ACTIONS = {
  mnv: 1,
  fullName: 2,
  timeIn: 3,
  leaveType: 4,
  shift: 5,
};
export const MINIMAL_ATTENDANCE_ONLY_WITH_ACTIONS = {
  ...MINIMAL_ATTENDANCE_ONLY_NO_ACTIONS,
  actions: 6,
};
